Update FakeIP addresses and Ports
openBackhaul/TypeApprovalRegister pull request #123
Opened 2022-12-06 11:13 UTC by kmohr-soprasteria

Fixes #119

2022-12-08 12:08 UTC, IswaryaaS requested changes
In config.json file, the client entries for TypeApprovalRegister, OperationKeyManagement and CurrentController are missing in logical-termination-point list. We could also see this being not present in config file of version 1.0.0 as well. Though absence of these entries does not have any significant affect, just to maintain harmony between service.yaml file and config.yaml file, please let me know if we can add the entries here or can we raise a separate issue for adding the entries.
@openBackhaul , kindly requesting for your thoughts

2022-12-09 06:39 UTC, IswaryaaS reviewed
I observed few scenarios which is not related to this issue, please find them below. 
1. /v1/regard-application and /v1/document-approval-status - the pattern of release-number needs an update to "^([0-9]{1,2})\.([0-9]{1,2})\.([0-9]{1,2})$"
2. Since, the attribute name of "application-release-number" is updated to "release-number" in  similar services, can we also update them in /v1/regard-application and /v1/document-approval-status
Kindly let me know your views

2022-12-09 18:46 UTC, openBackhaul commented
Added HttpClients and TcpClients for TypeApprovalRegister, OperationKeyManagement and CurrentController in CONFIGfile as proposed.

Changed attribute name from _application-release-number_ to _release-number_ at _/v1/regard-application_ and _/v1/document-approval-status_ as proposed.

Changed attribute name from _application-release-number_ to _release-number_ at _/v1/list-applications_, too.

Changed patterns for _release-number_ at _/v1/regard-application_ and _/v1/document-approval-status_ as proposed.

2022-12-12 07:06 UTC, IswaryaaS requested changes

2022-12-12 07:06 UTC, IswaryaaS commented on TypeApprovalRegister.yaml
>                    description: 'Subscribed for notifications about approval status updates'
As per the latest decision, to remove api-segment from http-s/c and tcp-s/c, the uuid's are updated in config and service list files. Similarly can we also update in OAS as well in this PR or shall we create a separate issue for updating the uuid(s) in OAS. Please let me know your views.

2022-12-12 07:15 UTC, IswaryaaS commented on TypeApprovalRegister.yaml
>                    description: 'Subscribed for notifications about approval status updates'
A separate issue has been already created for this purpose. hence resolving the conversation.

2022-12-12 08:35 UTC, openBackhaul commented on TypeApprovalRegister+config.json
> +            "uuid": "tar-2-0-0-http-c-tar-1-0-0-000",
Changed as proposed.

2022-12-12 08:37 UTC, openBackhaul commented on TypeApprovalRegister+config.json
> +            "uuid": "tar-2-0-0-tcp-c-tar-1-0-0-000",
Changed as proposed.

2022-12-12 08:38 UTC, openBackhaul commented on TypeApprovalRegister+config.json
> +              "tar-2-0-0-tco-c-cc-1-0-0-000"
Corrected as proposed.

2022-12-12 08:40 UTC, openBackhaul commented
Many thanks for reviewing.

2022-12-12 09:19 UTC, IswaryaaS approved these changes

2022-12-12 11:17 UTC, merged